"""Add fields

Revision ID: 00658cefafbe
Revises: 34bcbe8437f3
Create Date: 2025-03-21 11:27:11.015088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00658cefafbe'
down_revision: Union[str, None] = '34bcbe8437f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('sentiment_label', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('sentiment_score', sa.Float(), nullable=True))
    op.drop_column('articles', 'positive_sentiment')
    op.drop_column('articles', 'negative_sentiment')
    op.drop_column('articles', 'neutral_sentiment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('neutral_sentiment', sa.FLOAT(), nullable=True))
    op.add_column('articles', sa.Column('negative_sentiment', sa.FLOAT(), nullable=True))
    op.add_column('articles', sa.Column('positive_sentiment', sa.FLOAT(), nullable=True))
    op.drop_column('articles', 'sentiment_score')
    op.drop_column('articles', 'sentiment_label')
    # ### end Alembic commands ###
