"""Initial

Revision ID: 321bcbc186bf
Revises: a9008c475a5e
Create Date: 2025-03-21 10:50:24.200259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '321bcbc186bf'
down_revision: Union[str, None] = 'a9008c475a5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('published_time', sa.DateTime(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('authors', sa.String(), nullable=True),
    sa.Column('section_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    # ### end Alembic commands ###
