"""Add fields

Revision ID: 34bcbe8437f3
Revises: 321bcbc186bf
Create Date: 2025-03-21 11:13:54.604911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34bcbe8437f3'
down_revision: Union[str, None] = '321bcbc186bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('positive_sentiment', sa.Float(), nullable=True))
    op.add_column('articles', sa.Column('neutral_sentiment', sa.Float(), nullable=True))
    op.add_column('articles', sa.Column('negative_sentiment', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'negative_sentiment')
    op.drop_column('articles', 'neutral_sentiment')
    op.drop_column('articles', 'positive_sentiment')
    # ### end Alembic commands ###
