"""Add topic

Revision ID: b9c570ad6bb9
Revises: 00658cefafbe
Create Date: 2025-03-21 12:05:17.595105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9c570ad6bb9'
down_revision: Union[str, None] = '00658cefafbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('topic', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('topic_probability', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'topic_probability')
    op.drop_column('articles', 'topic')
    # ### end Alembic commands ###
